spring.application.name=Contact
server.error.include-message=always

#URL DO MEU BANCO DE DADOS
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/Contatos
spring.datasource.username=root
spring.datasource.password=Igr031
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
